on :
    issues:
        types: [reopened]

jobs:
    pdf-2-png:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
        - name: checkout
          id: checkout
          uses: actions/checkout@v3

        - name: update pip & install requirements
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

        - name: download pdf
          env:
            PDF_URL: ${{ secrets.PDF_URL }}
          run: |
                wget --no-check-certificate $PDF_URL -O pdf.pdf

        - name: convert pdf to png
          run: |
                python pdf_2_png.py pdf.pdf

        - name: translate png files
          env:
            NAVER_APPLICATION_ID: ${{ secrets.NAVER_APPLICATION_ID }}
            NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
            SRC: ${{ secrets.SRC }}
            TGT: ${{ secrets.TGT }}
          run: |
                python py_papago_img.py

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: target_png
            path: ./target/
            retention-days: 5
