on :
    push:
        branches:
            - main
            - dev
    issues:
        types: [reopened]

jobs:
    pdf-2-png:
        runs-on: ubuntu-latest
        timeout-minutes: 50
        steps:
        - name: checkout
          id: checkout
          uses: actions/checkout@v3

        - name: update pip & install requirements
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

        - name: download png
          env:
            PNG_URL: ${{ secrets.PNG_URL }}
          run: |
                pip install gdown
                gdown --no-check-certificate --remaining-ok -O pdf2png --folder $PNG_URL
                ls -l pdf2png

        - name: translate png files
          env:
            NAVER_APPLICATION_ID: ${{ secrets.NAVER_APPLICATION_ID }}
            NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
            SRC: ${{ secrets.SRC }}
            TGT: ${{ secrets.TGT }}
          run: |
                python py_papago_img.py

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: target_png
            path: ./target/
            retention-days: 5
